nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:3000', 'http://172.19.112.1:3000']  # Ajouter ici l'adresse de ton frontend React
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
  paths:
    '^/api/': ~
