<?php

namespace ContainerKw9ESIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nrh9xqqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nrh9xqq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nrh9xqq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', '.errored.36yoyFe', NULL, 'Cannot determine controller argument for "App\\Controller\\CategoryController::getCategories()": the $categoryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CategoryRepository". Did you forget to add a use statement?'],
        ], [
            'categoryRepository' => '?',
        ]);
    }
}
