<?php

namespace ContainerKw9ESIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RZWyvhOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RZWyvhO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RZWyvhO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::getCategories' => ['privates', '.service_locator.Nrh9xqq', 'get_ServiceLocator_Nrh9xqqService', true],
            'App\\Controller\\CategoryController::createCategory' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CategoryController::createCategory()', 'getCategoryControllercreateCategoryService', true],
            'App\\Controller\\CategoryController::updateCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::updateCategory()', 'getCategoryControllerupdateCategoryService', true],
            'App\\Controller\\CategoryController::deleteCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::deleteCategory()', 'getCategoryControllerdeleteCategoryService', true],
            'App\\Controller\\ProductController::getProducts' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::getProducts()', 'getProductControllergetProductsService', true],
            'App\\Controller\\ProductController::createProduct' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProductController::createProduct()', 'getProductControllercreateProductService', true],
            'App\\Controller\\ProductController::updateProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::updateProduct()', 'getProductControllerupdateProductService', true],
            'App\\Controller\\ProductController::deleteProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::deleteProduct()', 'getProductControllerdeleteProductService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:getCategories' => ['privates', '.service_locator.Nrh9xqq', 'get_ServiceLocator_Nrh9xqqService', true],
            'App\\Controller\\CategoryController:createCategory' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CategoryController::createCategory()', 'getCategoryControllercreateCategoryService', true],
            'App\\Controller\\CategoryController:updateCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::updateCategory()', 'getCategoryControllerupdateCategoryService', true],
            'App\\Controller\\CategoryController:deleteCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::deleteCategory()', 'getCategoryControllerdeleteCategoryService', true],
            'App\\Controller\\ProductController:getProducts' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::getProducts()', 'getProductControllergetProductsService', true],
            'App\\Controller\\ProductController:createProduct' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProductController::createProduct()', 'getProductControllercreateProductService', true],
            'App\\Controller\\ProductController:updateProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::updateProduct()', 'getProductControllerupdateProductService', true],
            'App\\Controller\\ProductController:deleteProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::deleteProduct()', 'getProductControllerdeleteProductService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::getCategories' => '?',
            'App\\Controller\\CategoryController::createCategory' => '?',
            'App\\Controller\\CategoryController::updateCategory' => '?',
            'App\\Controller\\CategoryController::deleteCategory' => '?',
            'App\\Controller\\ProductController::getProducts' => '?',
            'App\\Controller\\ProductController::createProduct' => '?',
            'App\\Controller\\ProductController::updateProduct' => '?',
            'App\\Controller\\ProductController::deleteProduct' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:getCategories' => '?',
            'App\\Controller\\CategoryController:createCategory' => '?',
            'App\\Controller\\CategoryController:updateCategory' => '?',
            'App\\Controller\\CategoryController:deleteCategory' => '?',
            'App\\Controller\\ProductController:getProducts' => '?',
            'App\\Controller\\ProductController:createProduct' => '?',
            'App\\Controller\\ProductController:updateProduct' => '?',
            'App\\Controller\\ProductController:deleteProduct' => '?',
        ]);
    }
}
