<?php

namespace ContainerN6kCKA4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::createCategory' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CategoryController::createCategory()', 'getCategoryControllercreateCategoryService', true],
            'App\\Controller\\CategoryController::updateCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::updateCategory()', 'getCategoryControllerupdateCategoryService', true],
            'App\\Controller\\CategoryController::deleteCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::deleteCategory()', 'getCategoryControllerdeleteCategoryService', true],
            'App\\Controller\\ProductController::createProduct' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProductController::createProduct()', 'getProductControllercreateProductService', true],
            'App\\Controller\\ProductController::updateProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::updateProduct()', 'getProductControllerupdateProductService', true],
            'App\\Controller\\ProductController::deleteProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::deleteProduct()', 'getProductControllerdeleteProductService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:createCategory' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CategoryController::createCategory()', 'getCategoryControllercreateCategoryService', true],
            'App\\Controller\\CategoryController:updateCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::updateCategory()', 'getCategoryControllerupdateCategoryService', true],
            'App\\Controller\\CategoryController:deleteCategory' => ['privates', '.service_locator.2S0AJ0M.App\\Controller\\CategoryController::deleteCategory()', 'getCategoryControllerdeleteCategoryService', true],
            'App\\Controller\\ProductController:createProduct' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProductController::createProduct()', 'getProductControllercreateProductService', true],
            'App\\Controller\\ProductController:updateProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::updateProduct()', 'getProductControllerupdateProductService', true],
            'App\\Controller\\ProductController:deleteProduct' => ['privates', '.service_locator.RIRrHzM.App\\Controller\\ProductController::deleteProduct()', 'getProductControllerdeleteProductService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::createCategory' => '?',
            'App\\Controller\\CategoryController::updateCategory' => '?',
            'App\\Controller\\CategoryController::deleteCategory' => '?',
            'App\\Controller\\ProductController::createProduct' => '?',
            'App\\Controller\\ProductController::updateProduct' => '?',
            'App\\Controller\\ProductController::deleteProduct' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:createCategory' => '?',
            'App\\Controller\\CategoryController:updateCategory' => '?',
            'App\\Controller\\CategoryController:deleteCategory' => '?',
            'App\\Controller\\ProductController:createProduct' => '?',
            'App\\Controller\\ProductController:updateProduct' => '?',
            'App\\Controller\\ProductController:deleteProduct' => '?',
        ]));
    }
}
