<?php

namespace ContainerGQ09NV6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerupdateProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RIRrHzM.App\Controller\ProductController::updateProduct()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RIRrHzM.App\\Controller\\ProductController::updateProduct()'] = ($container->privates['.service_locator.RIRrHzM'] ?? $container->load('get_ServiceLocator_RIRrHzMService'))->withContext('App\\Controller\\ProductController::updateProduct()', $container);
    }
}
