# config/routes.yaml

# Route pour créer une catégorie
create_category:
    path: /api/categories
    controller: App\Controller\CategoryController::createCategory
    methods: [POST]

# Route pour mettre à jour une catégorie
update_category:
    path: /api/categories/{id}
    controller: App\Controller\CategoryController::updateCategory
    methods: [PUT]

# Route pour supprimer une catégorie
delete_category:
    path: /api/categories/{id}
    controller: App\Controller\CategoryController::deleteCategory
    methods: [DELETE]

# Route pour récupérer toutes les catégories
get_categories:
    path: /api/categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]

# Route pour créer un produit
create_product:
    path: /api/products
    controller: App\Controller\ProductController::createProduct
    methods: [POST]

# Route pour mettre à jour un produit
update_product:
    path: /api/products/{id}
    controller: App\Controller\ProductController::updateProduct
    methods: [PUT]

# Route pour supprimer un produit
delete_product:
    path: /api/products/{id}
    controller: App\Controller\ProductController::deleteProduct
    methods: [DELETE]

# Route pour récupérer tous les produits
get_products:
    path: /api/products
    controller: App\Controller\ProductController::getProducts
    methods: [GET]
