<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGQ09NV6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGQ09NV6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGQ09NV6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGQ09NV6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGQ09NV6\App_KernelDevDebugContainer([
    'container.build_hash' => 'GQ09NV6',
    'container.build_id' => 'd19a600f',
    'container.build_time' => 1733234389,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGQ09NV6');
